name: Linux

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Install dependencies
      shell: bash
      run: |
       cd scripts
       ./install_dependencies.sh
       ./install_conan.sh

    - name: Configure Potato CMake
      shell: bash
      env:
        CC:   gcc-9
        CXX:  g++-9
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build Potato CMake
      shell: bash
      env:
        CC:   gcc-9
        CXX:  g++-9
      run: cmake --build build --config Release

